services:
  web:
    ports:
       - "80:80"
       - "443:443"
  ssh:
    ports:
       - "2222:22"
volumes:
  data-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${HOME}/svn-data"
